#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
test_root="$(mktemp -d)"
trap 'rm -rf "$test_root"' EXIT

mkdir -p "$test_root/scripts" "$test_root/api/proto/membrane/v1" \
  "$test_root/api/grpc/gen/membranev1" "$test_root/fixtures"
cp "$repo_root/scripts/check-go-proto-sync.sh" "$test_root/scripts/"
touch "$test_root/api/proto/membrane/v1/membrane.proto"

# Substitute generation, leaving the real sync checker and its file comparison
# intact so these fixtures exercise which changes it accepts and rejects.
cat >"$test_root/scripts/protoc-go.sh" <<'GENERATOR'
#!/usr/bin/env bash
set -euo pipefail
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
for arg in "$@"; do
  case "$arg" in
    --go_out=*) cp "$repo_root/fixtures/membrane.pb.go" "${arg#*=}/membrane.pb.go" ;;
    --go-grpc_out=*) cp "$repo_root/fixtures/membrane_grpc.pb.go" "${arg#*=}/membrane_grpc.pb.go" ;;
  esac
done
GENERATOR
chmod +x "$test_root/scripts/protoc-go.sh"

write_fixture() {
  local compiler_version="$1"
  local generator_version="${2:-1.36.11}"
  local descriptor="${3:-original}"
  cat >"$test_root/fixtures/membrane.pb.go" <<GO
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v$generator_version
// 	protoc        v$compiler_version
// source: membrane.proto

package membranev1

// protoc v7.35.1
const descriptor = "$descriptor"
GO
  cat >"$test_root/fixtures/membrane_grpc.pb.go" <<GO
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v$compiler_version
// source: membrane.proto

package membranev1
GO
}

expect_pass() {
  if ! bash "$test_root/scripts/check-go-proto-sync.sh" >"$test_root/output" 2>&1; then
    cat "$test_root/output" >&2
    echo "Expected proto sync to accept $1" >&2
    exit 1
  fi
}

expect_failure() {
  if bash "$test_root/scripts/check-go-proto-sync.sh" >"$test_root/output" 2>&1; then
    cat "$test_root/output" >&2
    echo "Expected proto sync to reject $1" >&2
    exit 1
  fi
}

write_fixture 7.35.1
cp "$test_root/fixtures/"*.go "$test_root/api/grpc/gen/membranev1/"
expect_pass 'identical stubs'

write_fixture 3.21.12
expect_pass 'only compiler-version metadata changing in both generator formats'

write_fixture 3.21.12 1.36.10
expect_failure 'a Go generator version change'

write_fixture 3.21.12 1.36.11 changed
expect_failure 'a generated descriptor change'

write_fixture 3.21.12
sed 's@^// protoc v7.35.1$@// protoc v3.21.12@' \
  "$test_root/fixtures/membrane.pb.go" >"$test_root/changed.go"
mv "$test_root/changed.go" "$test_root/fixtures/membrane.pb.go"
expect_failure 'a compiler-like comment outside the version header'

write_fixture 3.21.12
sed 's@protoc-gen-go-grpc v1.6.0@protoc-gen-go-grpc v1.6.1@' \
  "$test_root/fixtures/membrane_grpc.pb.go" >"$test_root/changed.go"
mv "$test_root/changed.go" "$test_root/fixtures/membrane_grpc.pb.go"
expect_failure 'a gRPC generator version change'

write_fixture 3.21.12
rm "$test_root/api/grpc/gen/membranev1/membrane.pb.go"
expect_failure 'a missing checked-in stub'
cp "$test_root/fixtures/membrane.pb.go" "$test_root/api/grpc/gen/membranev1/"

printf '#!/usr/bin/env bash\nexit 0\n' >"$test_root/scripts/protoc-go.sh"
expect_failure 'missing generator output'

printf '#!/usr/bin/env bash\nexit 9\n' >"$test_root/scripts/protoc-go.sh"
expect_failure 'a generator failure'

echo 'Go proto sync self-test passed (9 cases).'
